### ISSUE TITLE
500 on default glitchtip webhook

### ISSUE THREAD

**Issue by ayushin** [moan0s/alertbot#7]
`curl -X POST -d '{"alias": "GlitchTip", "text": "GlitchTip Alert", "attachments": [{"title": "TypeError: exceptions must derive from BaseException", "title_link": "https://alerts.djangoflow.net/getease-bv/issues/61126", "text": "django.core.management.commands.shell in <module>", "image_url": null, "color": "#e52b50", "fields": [{"title": "Project", "value": "Django", "short": true}, {"title": "Environment", "value": "sandbox", "short": true}], "mrkdown_in": ["text"]}], "sections": [{"activityTitle": "TypeError: exceptions must derive from BaseException", "activitySubtitle": "[View Issue DJANGO-1KR3](https://alerts.djangoflow.net/getease-bv/issues/61126)"}]}' 'https://matrix.............../_matrix/maubot/plugin/alerts/webhook/!.........:............'`

500 Internal Server Error

**Comment by moan0s** [comment]
I would need to see the log of the bot too to make sure but this is probably the parser not working with this type of error. Please note alertbot currently only works with
* Grafana
* Alertmanger
* Uptime-kuma
alerts. If you want to support this type of alert feel free to open a PR for it
